### ISSUE TITLE
Error! Bad return status for module build on kernel:

### ISSUE THREAD

**Issue by KONEY** [marqs85/db9_gpio_rpi#5]
I'm not sure it's me doing something wrong or a real issue but at this point I'm so stuck and need a  bit of help compiling.

I can't go past the building stage, the command will elaborate for a while before failing with this message:

`osmc@osmc:~$ sudo dkms build db9_gpio_rpi/1.2`
`Kernel preparation unnecessary for this kernel.  Skipping...`
`Building module:`
`cleaning build area...`
`make -j4 KERNELRELEASE=4.14.78-4-osmc all KVERSION=4.14.78-4-osmc....(bad exit status: 2)`
`Error! Bad return status for module build on kernel: 4.14.78-4-osmc (armv7l)`
`Consult /var/lib/dkms/db9_gpio_rpi/1.2/build/make.log for more information.`
`osmc@osmc:~$`

make.log attached.

Any hint will be very appreciated.

[make.log](https://github.com/marqs85/db9_gpio_rpi/files/3424180/make.log)

**Comment by marqs85** [comment]
It seems that ebcf03d introduced a bug in form of missing semicolon. ffe5bba should fix the compilation.

**Comment by marqs85** [comment]
Closing the issue.
